fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 5.0.1
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 5.1.0
    yumrepo_core:
      repo: git://github.com/puppetlabs/puppetlabs-yumrepo_core
      ref: 1.0.1
      puppet_version: ">= 6.0.0"
    chocolatey:
      repo: git://github.com/puppetlabs/puppetlabs-chocolatey.git
      ref: 3.0.0
    # Needed by chocolatey
    registry:
      repo: git://github.com/puppetlabs/puppetlabs-registry.git
      ref: 1.0.0
    # Needed by chocolatey
    powershell:
      repo: git://github.com/puppetlabs/puppetlabs-powershell.git
      ref: 1.0.1
    # Need by postgresql
    augeas_core:
      repo: git://github.com/puppetlabs/puppetlabs-augeas_core
      ref: 1.0.4
      puppet_version: ">= 6.0.0"
    # Need by postgresql
    concat:
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
      ref: v6.0.0
    postgresql:
      repo: git://github.com/puppetlabs/puppetlabs-postgresql.git
      ref: v6.0.0
    archive:
      repo: git://github.com/voxpupuli/puppet-archive.git
      ref: 'v3.0.0'
  symlinks:
    sensu: "#{source_dir}"
