---
language: ruby

bundler_args: --without system_tests development

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update bundler
  - gem --version
  - bundle -v
  - 'if [ -n "$encrypted_f942601034d6_key" -a -n "$encrypted_f942601034d6_iv" ]; then openssl aes-256-cbc -K $encrypted_f942601034d6_key -iv $encrypted_f942601034d6_iv -in tests/secrets.tar.enc -out tests/secrets.tar -d; cd tests && tar xvf secrets.tar ; fi'
sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec strings:generate reference'

matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 5"
    script: 'SPEC_OPTS="--format documentation" bundle exec rake spec'
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5" FIXTURES_YML=".fixtures-latest.yml"
  - rvm: 2.5.3
    env: PUPPET_GEM_VERSION="~> 6"
  - rvm: 2.5.3
    env: PUPPET_GEM_VERSION="~> 6" FIXTURES_YML=".fixtures-latest.yml"
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_sensu_full=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_full=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_full=yes BEAKER_sensu_ci_build=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="centos-7-cluster" BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_sensu_cluster=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-7-cluster" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_cluster=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-7-cluster" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_cluster=yes BEAKER_sensu_ci_build=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-2" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-2" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-2" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-201803" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-201803" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-201803" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
    bundler_args:
    script: bundle exec rake beaker
  allow_failures:
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5" FIXTURES_YML=".fixtures-latest.yml"
  - rvm: 2.5.3
    env: PUPPET_GEM_VERSION="~> 6" FIXTURES_YML=".fixtures-latest.yml"
  - rvm: 2.5.3
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
  - rvm: 2.5.3
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_full=yes BEAKER_sensu_ci_build=yes
  - rvm: 2.5.3
    env: BEAKER_set="centos-7-cluster" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_cluster=yes BEAKER_sensu_ci_build=yes
  - rvm: 2.5.3
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
  - rvm: 2.5.3
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
  - rvm: 2.5.3
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
  - rvm: 2.5.3
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
  - rvm: 2.5.3
    env: BEAKER_set="amazonlinux-2" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
  - rvm: 2.5.3
    env: BEAKER_set="amazonlinux-201803" BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_sensu_ci_build=yes
notifications:
  email: false
  slack:
    rooms:
      - secure: R1ThBe5UcmcX5UqnMAWEl5e0JpO1MjsCJDvsDfgTZQ7Nb7gYzj6T9lls11HxxoALffkdMbi7g7qlrwQ9ajblIZlS27aMbucwaMbWt6uiepVITHTub6+ZhM1yAcgFgRk2HsfaZnaB0LERW4SIfTTe/hGFIMgHGDYSf+NYqM3ikhY=
    on_success: change
    on_failure: always
