version: '{build}-{branch}'
platform:
  - x64
build: off
max_jobs: 2
branches:
  only:
    - master
    - /^v\d/
init:
- ps: $env:GEM_SOURCE = "http://rubygems.org"
install:
- set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
- ps: |
    if (!(Test-Path C:\downloads)) { mkdir C:\downloads | Out-Null }
    $log = "C:/puppet-agent.log"
    $agent_url = "https://downloads.puppetlabs.com/windows/${ENV:PUPPET_REPO}/puppet-agent-x64-latest.msi"
    Write-Output "Installing Puppet from $agent_url"
    Write-Output "Log will be written to $log"
    if ( Test-Path $log ) { Remove-Item $log }
    cd C:\downloads
    if (!(Test-Path "puppet-agent-x64-latest.msi")) { Start-FileDownload $agent_url }
    Start-Process msiexec.exe -Wait -NoNewWindow -ArgumentList @("/i", "C:\downloads\puppet-agent-x64-latest.msi", "/qn", "/l*", "$log")
    cd $ENV:APPVEYOR_BUILD_FOLDER
- ps: Copy-Item -Path $ENV:APPVEYOR_BUILD_FOLDER -Destination C:/ProgramData/PuppetLabs/code/environments/production/modules/sensu -Recurse
- ps: Copy-Item -Path "${ENV:APPVEYOR_BUILD_FOLDER}/tests/ssl" -Destination C:/ProgramData/PuppetLabs/puppet/etc/ssl -Recurse
- ps: Copy-Item -Path "${ENV:APPVEYOR_BUILD_FOLDER}/lib/facter" -Destination C:/ProgramData/PuppetLabs/puppet/cache/lib/facter -Recurse
- choco install puppet-bolt
- set PATH=C:\Program Files\Puppet Labs\Puppet\bin;%PATH%
- puppet --version
- puppet module install puppetlabs-stdlib
- puppet module install puppetlabs-chocolatey
- puppet module install puppet-archive
- puppet module install puppet-windows_env
- puppet module install richardc-datacat
- puppet config set --section main certname sensu_agent
- facter -p --debug
- ruby -v
- bundle -v
- bundle install --jobs 4 --retry 2 --path C:\vendor\bundle --without documentation
test_script:
- bundle exec rake acceptance:windows
- '"C:\\Program Files\\sensu\\sensu-agent\\bin\\sensu-agent.exe" service uninstall'
- 'puppet resource package "Sensu Agent" ensure=absent'
- rmdir C:\\ProgramData\\PuppetLabs\\code\\environments\\production\\modules /s /q
- ps: Copy-Item -Path $ENV:APPVEYOR_BUILD_FOLDER -Destination C:/ProgramData/PuppetLabs/code/environments/production/modules/sensu -Recurse
- set BEAKER_skip_apply=yes
- '"C:\Program Files\Puppet Labs\Bolt\bin\bolt" task show'
- '"C:\Program Files\Puppet Labs\Bolt\bin\bolt" --debug task run sensu::install_agent backend=sensu_backend:8081 subscription=windows output=true --targets localhost'
- bundle exec rake acceptance:windows
image:
  # Windows 2012 R2
  - Visual Studio 2015
  # Windows 2016
  - Visual Studio 2017
  # Windows 2019
  - Visual Studio 2019
environment:
  matrix:
    - PUPPET_GEM_VERSION: '~>5.x'
      PUPPET_REPO: puppet5
      RUBY_VERSION: 24-x64
    - PUPPET_GEM_VERSION: '~>6.x'
      PUPPET_REPO: puppet6
      RUBY_VERSION: 25-x64
matrix:
  fast_finish: false
